
package com.mmdc.motor_ph_portal.AdminAccess;

import com.mmdc.motor_ph_util.DatabaseConnect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.WindowConstants;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.stream.Stream;
import javax.swing.JOptionPane;



public class EmployeeProfileTabbed extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DatabaseConnect dbConnect = new DatabaseConnect() {};

    public EmployeeProfileTabbed() {
        
        initComponents();
        setTitle("Motor PH Employee Profile");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        //Displaying date and Time
        time();
        date();
        conn = dbConnect.connect();
        autoFillEmployeeId();
    }

    public final void time() {
        DateTimeFormatter times = DateTimeFormatter.ofPattern("hh:mm:ss a");
        LocalDateTime now = LocalDateTime.now();
        time.setText(times.format(now));
        time1.setText(times.format(now));
    }

    public final void date() {
        DateTimeFormatter dates = DateTimeFormatter.ofPattern("MMMM d, y");
        LocalDateTime now = LocalDateTime.now();
        date.setText(dates.format(now));
        date1.setText(dates.format(now));
    }

    public final void clear() {
        // Clear data from textbox
        searchId_field.setText("");
        searchFirstname_field.setText("");
        searchLastname_field.setText("");
        searchBday_field.setText("");
        searchStreet_field.setText("");
        searchBrgy_field.setText("");
        searchCity_field.setText("");
        searchProvince_field.setText("");
        searchPostalcode_field.setText("");
        searchContact_field.setText("");
        searchEmail_field.setText("");
        searchSss_field.setText("");
        searchPhhealth_field.setText("");
        searchPagibig_field.setText("");
        searchTin_field.setText("");
        firstname_field.setText("");
        lastname_field.setText("");
        bday_field.setText("");
        street_field.setText("");
        brgy_field.setText("");
        city_field.setText("");
        province_field.setText("");
        postalcode_field.setText("");
        contact_field.setText("");
        email_field.setText("");
        sss_field.setText("");
        phhealth_field.setText("");
        pagibig_field.setText("");
        tin_field.setText("");
    }
 
  public void autoFillEmployeeId() {
    try {
        int nextEmployeeId = dbConnect.getNextEmployeeId(); // Call the method

        if (id_field != null) {
            id_field.setText(String.valueOf(nextEmployeeId));
            id_field.setEditable(false); // Prevent manual editing
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error generating Employee ID: " + e.getMessage());

        if (id_field != null) {
            id_field.setText("10001"); // Fallback
        }
    }
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        mainPanel = new javax.swing.JPanel();
        greetings = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        noe_title = new javax.swing.JLabel();
        b_title = new javax.swing.JLabel();
        cn_title = new javax.swing.JLabel();
        en_title = new javax.swing.JLabel();
        email_title = new javax.swing.JLabel();
        searchFirstname_field = new javax.swing.JTextField();
        searchBday_field = new javax.swing.JTextField();
        searchContact_field = new javax.swing.JTextField();
        searchId_field = new javax.swing.JTextField();
        searchEmail_field = new javax.swing.JTextField();
        govIdNum_title = new javax.swing.JLabel();
        sss_title = new javax.swing.JLabel();
        pagibig_title = new javax.swing.JLabel();
        phhealth_title = new javax.swing.JLabel();
        tin_title = new javax.swing.JLabel();
        searchSss_field = new javax.swing.JTextField();
        searchPagibig_field = new javax.swing.JTextField();
        searchPhhealth_field = new javax.swing.JTextField();
        searchTin_field = new javax.swing.JTextField();
        searchBackButton = new javax.swing.JButton();
        searchClearButton = new javax.swing.JButton();
        noe_title1 = new javax.swing.JLabel();
        searchLastname_field = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        searchUpdateBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        address_title = new javax.swing.JLabel();
        searchStreet_field = new javax.swing.JTextField();
        searchDeleteBtn = new javax.swing.JButton();
        searchCity_field = new javax.swing.JTextField();
        searchBrgy_field = new javax.swing.JTextField();
        address_title1 = new javax.swing.JLabel();
        address_title2 = new javax.swing.JLabel();
        address_title3 = new javax.swing.JLabel();
        searchProvince_field = new javax.swing.JTextField();
        address_title4 = new javax.swing.JLabel();
        searchPostalcode_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mainPanel1 = new javax.swing.JPanel();
        greetings1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LOGO1 = new javax.swing.JLabel();
        noe_title2 = new javax.swing.JLabel();
        b_title1 = new javax.swing.JLabel();
        cn_title1 = new javax.swing.JLabel();
        en_title1 = new javax.swing.JLabel();
        email_title1 = new javax.swing.JLabel();
        firstname_field = new javax.swing.JTextField();
        bday_field = new javax.swing.JTextField();
        contact_field = new javax.swing.JTextField();
        id_field = new javax.swing.JTextField();
        email_field = new javax.swing.JTextField();
        govIdNum_title1 = new javax.swing.JLabel();
        sss_title1 = new javax.swing.JLabel();
        pagibig_title1 = new javax.swing.JLabel();
        phhealth_title1 = new javax.swing.JLabel();
        tin_title1 = new javax.swing.JLabel();
        sss_field = new javax.swing.JTextField();
        pagibig_field = new javax.swing.JTextField();
        phhealth_field = new javax.swing.JTextField();
        tin_field = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        noe_title3 = new javax.swing.JLabel();
        lastname_field = new javax.swing.JTextField();
        date1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        address_title5 = new javax.swing.JLabel();
        street_field = new javax.swing.JTextField();
        city_field = new javax.swing.JTextField();
        brgy_field = new javax.swing.JTextField();
        address_title6 = new javax.swing.JLabel();
        address_title7 = new javax.swing.JLabel();
        address_title8 = new javax.swing.JLabel();
        province_field = new javax.swing.JTextField();
        address_title9 = new javax.swing.JLabel();
        postalcode_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 43, 93));

        jPanel2.setBackground(new java.awt.Color(30, 43, 93));

        jTabbedPane2.setBackground(new java.awt.Color(253, 56, 29));
        jTabbedPane2.setForeground(new java.awt.Color(250, 250, 255));
        jTabbedPane2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        mainPanel.setBackground(new java.awt.Color(30, 43, 93));
        mainPanel.setForeground(new java.awt.Color(30, 43, 93));

        greetings.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        greetings.setForeground(new java.awt.Color(250, 250, 255));
        greetings.setText("Greetings!");

        jPanel1.setBackground(new java.awt.Color(250, 250, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(256, 70));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(92, 101, 138));
        jLabel1.setText("EMPLOYEE PROFILE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LOGO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(LOGO)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );

        noe_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        noe_title.setForeground(new java.awt.Color(250, 250, 255));
        noe_title.setText("First Name :");

        b_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        b_title.setForeground(new java.awt.Color(250, 250, 255));
        b_title.setText("Birthday :");

        cn_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cn_title.setForeground(new java.awt.Color(250, 250, 255));
        cn_title.setText("Contact Number:");

        en_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        en_title.setForeground(new java.awt.Color(250, 250, 255));
        en_title.setText("Employee Number :");

        email_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        email_title.setForeground(new java.awt.Color(250, 250, 255));
        email_title.setText("Email:");

        searchFirstname_field.setBackground(new java.awt.Color(250, 250, 255));
        searchFirstname_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchFirstname_field.setForeground(new java.awt.Color(92, 101, 138));

        searchBday_field.setBackground(new java.awt.Color(250, 250, 255));
        searchBday_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchBday_field.setForeground(new java.awt.Color(92, 101, 138));

        searchContact_field.setBackground(new java.awt.Color(250, 250, 255));
        searchContact_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchContact_field.setForeground(new java.awt.Color(92, 101, 138));

        searchId_field.setBackground(new java.awt.Color(250, 250, 255));
        searchId_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchId_field.setForeground(new java.awt.Color(92, 101, 138));

        searchEmail_field.setBackground(new java.awt.Color(250, 250, 255));
        searchEmail_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchEmail_field.setForeground(new java.awt.Color(92, 101, 138));

        govIdNum_title.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        govIdNum_title.setForeground(new java.awt.Color(250, 250, 255));
        govIdNum_title.setText("Government ID Numbers :");

        sss_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sss_title.setForeground(new java.awt.Color(250, 250, 255));
        sss_title.setText("SSS Number :");

        pagibig_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pagibig_title.setForeground(new java.awt.Color(250, 250, 255));
        pagibig_title.setText("PAG-IBIG Number :");

        phhealth_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        phhealth_title.setForeground(new java.awt.Color(250, 250, 255));
        phhealth_title.setText("PhilHealth Number :");

        tin_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tin_title.setForeground(new java.awt.Color(250, 250, 255));
        tin_title.setText("TIN :");

        searchSss_field.setBackground(new java.awt.Color(250, 250, 255));
        searchSss_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchSss_field.setForeground(new java.awt.Color(92, 101, 138));

        searchPagibig_field.setBackground(new java.awt.Color(250, 250, 255));
        searchPagibig_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchPagibig_field.setForeground(new java.awt.Color(92, 101, 138));

        searchPhhealth_field.setBackground(new java.awt.Color(250, 250, 255));
        searchPhhealth_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchPhhealth_field.setForeground(new java.awt.Color(92, 101, 138));

        searchTin_field.setBackground(new java.awt.Color(250, 250, 255));
        searchTin_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchTin_field.setForeground(new java.awt.Color(92, 101, 138));

        searchBackButton.setBackground(new java.awt.Color(253, 56, 29));
        searchBackButton.setForeground(new java.awt.Color(250, 250, 255));
        searchBackButton.setText("Back");
        searchBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBackButtonActionPerformed(evt);
            }
        });

        searchClearButton.setBackground(new java.awt.Color(253, 56, 29));
        searchClearButton.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        searchClearButton.setForeground(new java.awt.Color(250, 250, 255));
        searchClearButton.setText("Clear");
        searchClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchClearButtonActionPerformed(evt);
            }
        });

        noe_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        noe_title1.setForeground(new java.awt.Color(250, 250, 255));
        noe_title1.setText("Last Name :");

        searchLastname_field.setBackground(new java.awt.Color(250, 250, 255));
        searchLastname_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchLastname_field.setForeground(new java.awt.Color(92, 101, 138));

        date.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        date.setForeground(new java.awt.Color(250, 250, 255));
        date.setText("Date ");

        time.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        time.setForeground(new java.awt.Color(250, 250, 255));
        time.setText(" Time");

        searchUpdateBtn.setBackground(new java.awt.Color(253, 56, 29));
        searchUpdateBtn.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        searchUpdateBtn.setForeground(new java.awt.Color(250, 250, 255));
        searchUpdateBtn.setText("Update");
        searchUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUpdateBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(253, 56, 29));
        searchBtn.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(250, 250, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        address_title.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title.setForeground(new java.awt.Color(250, 250, 255));
        address_title.setText("Street Address:");

        searchStreet_field.setBackground(new java.awt.Color(250, 250, 255));
        searchStreet_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchStreet_field.setForeground(new java.awt.Color(92, 101, 138));

        searchDeleteBtn.setBackground(new java.awt.Color(253, 56, 29));
        searchDeleteBtn.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        searchDeleteBtn.setForeground(new java.awt.Color(250, 250, 255));
        searchDeleteBtn.setText("Delete");
        searchDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDeleteBtnActionPerformed(evt);
            }
        });

        searchCity_field.setBackground(new java.awt.Color(250, 250, 255));
        searchCity_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchCity_field.setForeground(new java.awt.Color(92, 101, 138));

        searchBrgy_field.setBackground(new java.awt.Color(250, 250, 255));
        searchBrgy_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchBrgy_field.setForeground(new java.awt.Color(92, 101, 138));

        address_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title1.setForeground(new java.awt.Color(250, 250, 255));
        address_title1.setText("Barangay:");

        address_title2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title2.setForeground(new java.awt.Color(250, 250, 255));
        address_title2.setText("City:");

        address_title3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title3.setForeground(new java.awt.Color(250, 250, 255));
        address_title3.setText("Province:");

        searchProvince_field.setBackground(new java.awt.Color(250, 250, 255));
        searchProvince_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchProvince_field.setForeground(new java.awt.Color(92, 101, 138));

        address_title4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title4.setForeground(new java.awt.Color(250, 250, 255));
        address_title4.setText("Postal Code:");

        searchPostalcode_field.setBackground(new java.awt.Color(250, 250, 255));
        searchPostalcode_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        searchPostalcode_field.setForeground(new java.awt.Color(92, 101, 138));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(92, 101, 138));
        jLabel3.setText("*yyyy-mm-dd");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(en_title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchId_field, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(noe_title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchFirstname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(noe_title1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchLastname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(address_title)
                                        .addGap(12, 12, 12))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(address_title2)
                                        .addGap(18, 18, 18)))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchCity_field, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchStreet_field, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_title, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cn_title, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(email_title, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchContact_field, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(searchBday_field)
                            .addComponent(searchEmail_field))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3))
                    .addComponent(searchBackButton)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pagibig_title, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sss_title, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(tin_title, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(phhealth_title, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(searchPhhealth_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(searchPagibig_field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchSss_field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchTin_field)))
                            .addComponent(govIdNum_title))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchUpdateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchClearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchDeleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(address_title4)
                        .addGap(18, 18, 18)
                        .addComponent(searchPostalcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(date)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(time))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(greetings))))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(address_title3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchProvince_field, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(address_title1)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchBrgy_field, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(greetings)
                .addGap(38, 38, 38)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchContact_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cn_title)
                    .addComponent(en_title)
                    .addComponent(searchId_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchEmail_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_title)
                    .addComponent(searchFirstname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noe_title))
                .addGap(4, 4, 4)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noe_title1)
                    .addComponent(searchBday_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_title)
                    .addComponent(jLabel3)
                    .addComponent(searchLastname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBrgy_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address_title1))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchStreet_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_title))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCity_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchProvince_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address_title4)
                        .addComponent(searchPostalcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address_title3)
                        .addComponent(address_title2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchUpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchDeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchClearButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(govIdNum_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sss_title)
                            .addComponent(searchSss_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pagibig_title)
                            .addComponent(searchPagibig_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phhealth_title)
                            .addComponent(searchPhhealth_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tin_title)
                            .addComponent(searchTin_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(searchBackButton)
                .addGap(11, 11, 11)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(time))
                .addContainerGap())
        );

        mainPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {searchBday_field, searchContact_field, searchEmail_field, searchFirstname_field, searchId_field, searchLastname_field, searchStreet_field});

        jTabbedPane2.addTab("Search/ Update/ Delete Employee", mainPanel);

        mainPanel1.setBackground(new java.awt.Color(30, 43, 93));
        mainPanel1.setForeground(new java.awt.Color(30, 43, 93));

        greetings1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        greetings1.setForeground(new java.awt.Color(250, 250, 255));
        greetings1.setText("Greetings!");

        jPanel3.setBackground(new java.awt.Color(250, 250, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(256, 70));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(92, 101, 138));
        jLabel4.setText("EMPLOYEE PROFILE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LOGO1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(178, 178, 178))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(LOGO1)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );

        noe_title2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        noe_title2.setForeground(new java.awt.Color(250, 250, 255));
        noe_title2.setText("First Name :");

        b_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        b_title1.setForeground(new java.awt.Color(250, 250, 255));
        b_title1.setText("Birthday :");

        cn_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cn_title1.setForeground(new java.awt.Color(250, 250, 255));
        cn_title1.setText("Contact Number:");

        en_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        en_title1.setForeground(new java.awt.Color(250, 250, 255));
        en_title1.setText("Employee Number :");

        email_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        email_title1.setForeground(new java.awt.Color(250, 250, 255));
        email_title1.setText("Email:");

        firstname_field.setBackground(new java.awt.Color(250, 250, 255));
        firstname_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        firstname_field.setForeground(new java.awt.Color(92, 101, 138));

        bday_field.setBackground(new java.awt.Color(250, 250, 255));
        bday_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        bday_field.setForeground(new java.awt.Color(92, 101, 138));

        contact_field.setBackground(new java.awt.Color(250, 250, 255));
        contact_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        contact_field.setForeground(new java.awt.Color(92, 101, 138));

        id_field.setEditable(false);
        id_field.setBackground(new java.awt.Color(250, 250, 255));
        id_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        id_field.setForeground(new java.awt.Color(92, 101, 138));

        email_field.setBackground(new java.awt.Color(250, 250, 255));
        email_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        email_field.setForeground(new java.awt.Color(92, 101, 138));

        govIdNum_title1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        govIdNum_title1.setForeground(new java.awt.Color(250, 250, 255));
        govIdNum_title1.setText("Government ID Numbers :");

        sss_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sss_title1.setForeground(new java.awt.Color(250, 250, 255));
        sss_title1.setText("SSS Number :");

        pagibig_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pagibig_title1.setForeground(new java.awt.Color(250, 250, 255));
        pagibig_title1.setText("PAG-IBIG Number :");

        phhealth_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        phhealth_title1.setForeground(new java.awt.Color(250, 250, 255));
        phhealth_title1.setText("PhilHealth Number :");

        tin_title1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tin_title1.setForeground(new java.awt.Color(250, 250, 255));
        tin_title1.setText("TIN :");

        sss_field.setBackground(new java.awt.Color(250, 250, 255));
        sss_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        sss_field.setForeground(new java.awt.Color(92, 101, 138));

        pagibig_field.setBackground(new java.awt.Color(250, 250, 255));
        pagibig_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        pagibig_field.setForeground(new java.awt.Color(92, 101, 138));

        phhealth_field.setBackground(new java.awt.Color(250, 250, 255));
        phhealth_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        phhealth_field.setForeground(new java.awt.Color(92, 101, 138));

        tin_field.setBackground(new java.awt.Color(250, 250, 255));
        tin_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tin_field.setForeground(new java.awt.Color(92, 101, 138));

        backButton.setBackground(new java.awt.Color(253, 56, 29));
        backButton.setForeground(new java.awt.Color(250, 250, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(253, 56, 29));
        clearButton.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(250, 250, 255));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        noe_title3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        noe_title3.setForeground(new java.awt.Color(250, 250, 255));
        noe_title3.setText("Last Name :");

        lastname_field.setBackground(new java.awt.Color(250, 250, 255));
        lastname_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lastname_field.setForeground(new java.awt.Color(92, 101, 138));

        date1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(250, 250, 255));
        date1.setText("Date ");

        time1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(250, 250, 255));
        time1.setText(" Time");

        addBtn.setBackground(new java.awt.Color(253, 56, 29));
        addBtn.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(250, 250, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        address_title5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title5.setForeground(new java.awt.Color(250, 250, 255));
        address_title5.setText("Street Address:");

        street_field.setBackground(new java.awt.Color(250, 250, 255));
        street_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        street_field.setForeground(new java.awt.Color(92, 101, 138));

        city_field.setBackground(new java.awt.Color(250, 250, 255));
        city_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        city_field.setForeground(new java.awt.Color(92, 101, 138));

        brgy_field.setBackground(new java.awt.Color(250, 250, 255));
        brgy_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        brgy_field.setForeground(new java.awt.Color(92, 101, 138));

        address_title6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title6.setForeground(new java.awt.Color(250, 250, 255));
        address_title6.setText("Barangay:");

        address_title7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title7.setForeground(new java.awt.Color(250, 250, 255));
        address_title7.setText("City:");

        address_title8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title8.setForeground(new java.awt.Color(250, 250, 255));
        address_title8.setText("Province:");

        province_field.setBackground(new java.awt.Color(250, 250, 255));
        province_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        province_field.setForeground(new java.awt.Color(92, 101, 138));

        address_title9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        address_title9.setForeground(new java.awt.Color(250, 250, 255));
        address_title9.setText("Postal Code:");

        postalcode_field.setBackground(new java.awt.Color(250, 250, 255));
        postalcode_field.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        postalcode_field.setForeground(new java.awt.Color(92, 101, 138));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(92, 101, 138));
        jLabel6.setText("*yyyy-mm-dd");

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addComponent(en_title1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(noe_title2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(firstname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                        .addComponent(noe_title3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastname_field))))
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addComponent(address_title5)
                                .addGap(18, 18, 18)
                                .addComponent(street_field, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mainPanel1Layout.createSequentialGroup()
                                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cn_title1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(email_title1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(contact_field, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(mainPanel1Layout.createSequentialGroup()
                                        .addComponent(address_title6)
                                        .addGap(18, 18, 18)
                                        .addComponent(brgy_field, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_title1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bday_field, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pagibig_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sss_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                        .addComponent(tin_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44))
                                    .addGroup(mainPanel1Layout.createSequentialGroup()
                                        .addComponent(phhealth_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)))
                                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tin_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pagibig_field, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sss_field, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phhealth_field, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(govIdNum_title1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(90, 90, 90))
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(greetings1))
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addComponent(date1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(time1))))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(address_title7)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(address_title8)
                                .addGap(18, 18, 18)
                                .addComponent(province_field, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                        .addComponent(address_title9)
                                        .addGap(18, 18, 18)
                                        .addComponent(postalcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                        .addComponent(city_field, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(393, 393, 393)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bday_field, contact_field, email_field, firstname_field, id_field});

        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(greetings1)
                .addGap(38, 38, 38)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cn_title1)
                    .addComponent(en_title1)
                    .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noe_title2)))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_title1)
                            .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(noe_title3)
                                .addComponent(lastname_field, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_title1)
                                    .addComponent(jLabel6))))
                        .addGap(20, 20, 20)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(brgy_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address_title6))
                            .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(street_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address_title5))))
                    .addComponent(bday_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(city_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address_title7))
                    .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(province_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address_title9)
                        .addComponent(postalcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(address_title8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                        .addComponent(govIdNum_title1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sss_title1)
                            .addComponent(sss_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pagibig_title1)
                            .addComponent(pagibig_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phhealth_title1)
                            .addComponent(phhealth_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tin_title1)
                            .addComponent(tin_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1)
                    .addComponent(time1))
                .addContainerGap())
        );

        mainPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bday_field, contact_field, email_field, firstname_field, id_field, lastname_field});

        jTabbedPane2.addTab("Add Employee", mainPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBackButtonActionPerformed
        // back to Employee Portal
        EmployeePortal employeePortal = new EmployeePortal();
        employeePortal.show();

        dispose();
    }//GEN-LAST:event_searchBackButtonActionPerformed

    private void searchClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchClearButtonActionPerformed

        clear();
    }//GEN-LAST:event_searchClearButtonActionPerformed

    private void searchUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUpdateBtnActionPerformed
        // Update Information from SQL

        String lastName = searchLastname_field.getText();
        String phoneNumber = searchContact_field.getText();
        String street = searchStreet_field.getText().trim();
        String barangay = searchBrgy_field.getText().trim();
        String city = searchCity_field.getText().trim();
        String province = searchProvince_field.getText().trim();
        String postalcode = searchPostalcode_field.getText().trim();
        String employeeID = searchId_field.getText();

        if (employeeID.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Employee ID!");
            return; // Exit if Employee ID is empty
        }

        Admin_Class employee = new Admin_Class(employeeID, null, lastName, null, null, null,
            street, barangay, city, province, postalcode, phoneNumber,
            null, null, null, null, null, null);

        if(employeeID.equals("")){
            JOptionPane.showMessageDialog(this, "Enter Employee ID!");
        }
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this?",
            "Employee Profile Updating...", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {

            dbConnect.updateEmployee(employee); // Call the updateEmployee method
        }

        else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Data not successfully updated!");
        }
    }//GEN-LAST:event_searchUpdateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // ADD EMPLOYEE RECORD
        String employeeId = searchId_field.getText();
        try {
            conn = dbConnect.connect();
            Admin_Class employee = dbConnect.getEmployeeDetails(employeeId);

            if (employee != null) {
                // Populate fields
                searchFirstname_field.setText(employee.getFirstName());
                searchLastname_field.setText(employee.getLastName());
                searchBday_field.setText(employee.getBirthday());
                searchEmail_field.setText(employee.getEmail());
                searchStreet_field.setText(employee.getStreet());
                searchBrgy_field.setText(employee.getBarangay());
                searchCity_field.setText(employee.getCity());
                searchProvince_field.setText(employee.getProvince());
                searchPostalcode_field.setText(employee.getPostalcode());
                searchContact_field.setText(employee.getPhoneNumber());
                searchSss_field.setText(employee.getSssNum());
                searchPagibig_field.setText(employee.getPagibigNum());
                searchPhhealth_field.setText(employee.getPhilHealthNum());
                searchTin_field.setText(employee.getTinNum());

                JOptionPane.showMessageDialog(null, "Employee profile found with ID: " + employeeId,
                    "Success", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "No employee found with ID: " + employeeId,
                    "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDeleteBtnActionPerformed
        // DELETE RECORD
        String employeeId = searchId_field.getText();

        if (employeeId.equals("")) {
            JOptionPane.showMessageDialog(this, "Enter Employee ID!");
        }

        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this?", "Employee Profile Deleting...", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {

            dbConnect.deleteEmployee(employeeId); // Call the deleteEmployee method

        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Employee Profile Deletion Not Successful!");
        }
    }//GEN-LAST:event_searchDeleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // ADD EMPLOYEE RECORD
        try {
            // 1. Collect and trim input values
            String firstName = firstname_field.getText().trim();
            String lastName = lastname_field.getText().trim();
            String birthday = bday_field.getText().trim();
            String street = street_field.getText().trim();
            String barangay = brgy_field.getText().trim();
            String city = city_field.getText().trim();
            String province = province_field.getText().trim();
            String postalcode = postalcode_field.getText().trim();
            String phoneNumber = contact_field.getText().trim();
            String email = email_field.getText().trim();
            String sssNum = sss_field.getText().trim();
            String philHealthNum = phhealth_field.getText().trim();
            String pagibigNum = pagibig_field.getText().trim();
            String tinNum = tin_field.getText().trim();

            // 2. Validate postal code
            if (postalcode.length() > 4 || !postalcode.matches("\\d{1,4}")) {
                JOptionPane.showMessageDialog(this,
                    "Postal code must be 1–4 digits.",
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Check if any required field is empty
            if (Stream.of(firstName, lastName, birthday, street, barangay, city, province,
                postalcode, phoneNumber, email, sssNum, philHealthNum, pagibigNum, tinNum)
            .anyMatch(String::isEmpty)) {
            JOptionPane.showMessageDialog(this,
                "All fields are required.",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Add address and get generated address ID
        int addressId = dbConnect.addAddressAndReturnId(
            street, barangay, city, province, postalcode
        );

        // 5. Create employee object with correct parameter order
        Admin_Class newEmployee = new Admin_Class(
            null, firstName, lastName, email, birthday, null, street,
            barangay, city, province, postalcode, phoneNumber,
            sssNum, philHealthNum, tinNum, pagibigNum,
            null,null
        );

        // 6. Insert employee and get generated ID
        int employeeId = dbConnect.addEmployeeAndReturnId(newEmployee, addressId);

        // 7. Display in form and show success
        searchId_field.setText(String.valueOf(employeeId));
        JOptionPane.showMessageDialog(this,
            "Employee added successfully!\nEmployee ID: " + employeeId +
            "\nAddress ID: " + addressId,
            "Success", JOptionPane.INFORMATION_MESSAGE);

        // 8. Clear form
        clear();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Database error: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "System error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // back to Employee Portal
        EmployeePortal employeePortal = new EmployeePortal();
        employeePortal.show();

        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfileTabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfileTabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfileTabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeProfileTabbed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeProfileTabbed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel LOGO1;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel address_title;
    private javax.swing.JLabel address_title1;
    private javax.swing.JLabel address_title2;
    private javax.swing.JLabel address_title3;
    private javax.swing.JLabel address_title4;
    private javax.swing.JLabel address_title5;
    private javax.swing.JLabel address_title6;
    private javax.swing.JLabel address_title7;
    private javax.swing.JLabel address_title8;
    private javax.swing.JLabel address_title9;
    private javax.swing.JLabel b_title;
    private javax.swing.JLabel b_title1;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bday_field;
    private javax.swing.JTextField brgy_field;
    private javax.swing.JTextField city_field;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel cn_title;
    private javax.swing.JLabel cn_title1;
    private javax.swing.JTextField contact_field;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_title;
    private javax.swing.JLabel email_title1;
    private javax.swing.JLabel en_title;
    private javax.swing.JLabel en_title1;
    private javax.swing.JTextField firstname_field;
    private javax.swing.JLabel govIdNum_title;
    private javax.swing.JLabel govIdNum_title1;
    private javax.swing.JLabel greetings;
    private javax.swing.JLabel greetings1;
    private javax.swing.JTextField id_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField lastname_field;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JLabel noe_title;
    private javax.swing.JLabel noe_title1;
    private javax.swing.JLabel noe_title2;
    private javax.swing.JLabel noe_title3;
    private javax.swing.JTextField pagibig_field;
    private javax.swing.JLabel pagibig_title;
    private javax.swing.JLabel pagibig_title1;
    private javax.swing.JTextField phhealth_field;
    private javax.swing.JLabel phhealth_title;
    private javax.swing.JLabel phhealth_title1;
    private javax.swing.JTextField postalcode_field;
    private javax.swing.JTextField province_field;
    private javax.swing.JButton searchBackButton;
    private javax.swing.JTextField searchBday_field;
    private javax.swing.JTextField searchBrgy_field;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchCity_field;
    private javax.swing.JButton searchClearButton;
    private javax.swing.JTextField searchContact_field;
    private javax.swing.JButton searchDeleteBtn;
    private javax.swing.JTextField searchEmail_field;
    private javax.swing.JTextField searchFirstname_field;
    private javax.swing.JTextField searchId_field;
    private javax.swing.JTextField searchLastname_field;
    private javax.swing.JTextField searchPagibig_field;
    private javax.swing.JTextField searchPhhealth_field;
    private javax.swing.JTextField searchPostalcode_field;
    private javax.swing.JTextField searchProvince_field;
    private javax.swing.JTextField searchSss_field;
    private javax.swing.JTextField searchStreet_field;
    private javax.swing.JTextField searchTin_field;
    private javax.swing.JButton searchUpdateBtn;
    private javax.swing.JTextField sss_field;
    private javax.swing.JLabel sss_title;
    private javax.swing.JLabel sss_title1;
    private javax.swing.JTextField street_field;
    private javax.swing.JLabel time;
    private javax.swing.JLabel time1;
    private javax.swing.JTextField tin_field;
    private javax.swing.JLabel tin_title;
    private javax.swing.JLabel tin_title1;
    // End of variables declaration//GEN-END:variables
}
