# Database Configuration
db.url=jdbc:mysql://localhost:3306/payrollsystem_db
db.user=root
db.password=enaxor

# Email Configuration
email.host=smtp.gmail.com
email.username=amotorph@gmail.com
email.password=znvm dejb erhe wink

# Application Configuration
app.name=MotorPH Employee Portal
app.version=1.0.0
